# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gethistoryfile', '0002_urlstore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrlOs',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='urlstore',
            old_name='last_visited',
            new_name='date_visited',
        ),
        migrations.RenameField(
            model_name='urlstore',
            old_name='username',
            new_name='search_text',
        ),
        migrations.RemoveField(
            model_name='urlstore',
            name='date_searched',
        ),
        migrations.RemoveField(
            model_name='urlstore',
            name='is_active',
        ),
    ]
